version: '3.8'

networks:
  backend_network:
    driver: bridge

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - DB_NAME=${DB_NAME_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
      - REDIS_PORT=${REDIS_PORT_DOCKER}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - mongo
      - redis_service
      - prometheus
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

  redis_service:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000" 
    environment:
      # - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend_network

volumes:
  mongo_data:
  grafana_data:
