global:
  scrape_interval: 5s
  # scrape_timeout: 10s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi_app:8000']



# global:
#   scrape_interval: 5s
#   scrape_timeout: 4s  # Increased timeout to prevent dropped scrapes

# scrape_configs:
#   - job_name: 'fastapi'
#     metrics_path: '/metrics'
#     honor_labels: true  # Preserve original labels
#     static_configs:
#       - targets: ['host.docker.internal:8000']  # Better for Dockerized setups