{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WebSocket  Total , Actice and Disconnected  Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "disconnected_connections_total{instance=\"fastapi_app:8000\", job=\"fastapi\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_connections_active{instance=\"fastapi_app:8000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ws_connections_total{instance=\"fastapi_app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu usage and  memory usage percent ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" },
    {},
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time taken to process WebSocket messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ws_message_processing_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total  ws messages  and total  ws connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ws_messages_total", "legendFormat": "__auto" },
    { "expr": "ws_connections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of active Redis channels AndTotal Redis channels created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_channels_active", "legendFormat": "__auto" },
    {},
    { "expr": "redis_channels_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total MongoDb Connection created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_connections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http requests total and ws active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" },
    { "expr": "ws_connections_active", "legendFormat": "__auto" }
   ]
  }
 ]
}